package Vaght.Models;
// Generated Dec 11, 2017 3:46:35 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Relations generated by hbm2java
 */
@Entity
@Table(name="relations"
    ,catalog="vaght"
)
public class Relations  implements java.io.Serializable {


     private Integer relationId;
     private String title;
     private Date era;
     private int statue;

    public Relations() {
    }

    public Relations(String title, Date era, int statue) {
       this.title = title;
       this.era = era;
       this.statue = statue;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="relationID", unique=true, nullable=false)
    public Integer getRelationId() {
        return this.relationId;
    }
    
    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }

    
    @Column(name="Title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Era", nullable=false, length=10)
    public Date getEra() {
        return this.era;
    }
    
    public void setEra(Date era) {
        this.era = era;
    }

    
    @Column(name="Statue", nullable=false)
    public int getStatue() {
        return this.statue;
    }
    
    public void setStatue(int statue) {
        this.statue = statue;
    }




}


